# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='\u6587\u4ef6\u540d')),
                ('category', models.CharField(blank=True, choices=[('1', '\u666e\u901a\u6587\u4ef6'), ('2', 'excel\u8868\u6587\u4ef6'), ('3', '\u56fe\u7247')], max_length=30, null=True, verbose_name='\u6587\u4ef6\u79cd\u7c7b')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='\u6587\u4ef6\u5185\u5bb9')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65e5\u671f')),
                ('username', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u4f20\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u603b\u8868',
                'verbose_name_plural': '\u6587\u4ef6\u603b\u8868',
            },
        ),
        migrations.CreateModel(
            name='excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=254, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65e5\u671f')),
                ('li_name', models.CharField(default='', max_length=256)),
                ('li_ctx', models.CharField(blank=True, max_length=10000, null=True, verbose_name='\u8be5\u884c\u5217\u5185\u5bb9')),
                ('li_num', models.IntegerField(default=0, verbose_name='\u5217\u53f7')),
                ('row_num', models.IntegerField(default=0, verbose_name='\u884c\u53f7')),
                ('excel_name', models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.all_file', to_field='filename', verbose_name='\u8868\u6587\u4ef6\u540d')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u4f20\u8005')),
            ],
            options={
                'verbose_name': '\u8868\u6587\u4ef6',
                'verbose_name_plural': '\u8868\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=254, unique=True, verbose_name='\u5217\u540d')),
                ('field_val', models.CharField(default='', max_length=254, verbose_name='\u6bcf\u4e2a\u5b57\u6bb5\u7684value\u503c')),
            ],
            options={
                'verbose_name': '\u5217\u540d',
                'verbose_name_plural': '\u5217\u540d',
            },
        ),
    ]
