# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180424_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='unit_mark',
            field=models.CharField(default='', max_length=20),
        ),
    ]
