# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_excel_unit_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='unit_mark',
            field=models.IntegerField(blank=True, default='', max_length=20),
        ),
    ]
