#coding:utf-8
"""
Django settings for zky_file project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .celeryconfig import *  # 导入Celery配置信息

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pibm=qn^16^ee5aog!r7%mrcm(gq4mo%(r#9b4hj#33hr4o_0z'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'index',
    'file',
    # 'upload',
    'search',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zky_file.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zky_file.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
   }
}
#
# DATABASES = {
# 	        'default': {
#  		'ENGINE': 'django.db.backends.mysql',# Add 'postgresql_psycopg2','mysql', 'sqlite3' or 'oracle'
#  		'NAME': 'zky',                     # Your db name, Or path to database file if using sqlite3
#  	    'USER':'zky',                        # Your db user name, Not used with sqlite3
#  		'PASSWORD':'zky123456',     #  Your db password, Not used with sqlite3
#  		'HOST':'127.0.0.1',                               #  Your db host, set to empty string('') for def
#  		'PORT':'3306',                      #  Your db port, set to empty string('') for default, Not used with sqlite3
#  		 }
#  		 }


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_URL = '/static/'
STATIC_URL = '/dist/'

'''静态资源地址'''
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "dist"),
    '/var/www/web/dist',
)

# TEMPLATE_DIRS=(  os.path.join(BASE_DIR, 'templates'),)
MEDIA_ROOT= os.path.join(BASE_DIR, 'all_files')
# print  'Media_root : %s' %MEDIA_ROOT

MEDIA_URLS= '/file/'
# print   'Media_urls:%s' %MEDIS_URLS
'''跳转地址'''
LOGIN_REDIRECT_URL = '/search'

'''中文风格的主题'''
SUIT_CONFIG = {
    'ADMIN_NAME': u'文件管理系统',
    'MENU': (
        'sites',
        {'app': 'index', 'label': u'文件管理'},
        {'app': 'search', 'label': u'搜索'},
    ),
}
''' haystack config'''

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'index.whoosh_cn_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

HAYSTACK_SIGNAL_PROCESSOR = "haystack.signals.RealtimeSignalProcessor"
#from haystack.signals import RealtimeSignalProcessor

SUIT_CONFIG = {
    'ADMIN_NAME': '后台管理中心',
    'MENU': ({'label': '用户',
              'app': '用户',
              'models': ('all_file','field','excel')},
             ),
    # 每一个字典表示左侧菜单的一栏
    # label表示name，app表示上边的install的app，models表示用了哪些models
}

'''一些服务器配置'''

IP='127.0.0.1'

PORT='8000'

# REDIS related settings
REDIS_HOST = '192.168.1.252'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'


